pg config constructor
theartofdevel/production-service pull request #1
Opened 2022-05-06 19:26 UTC by KindOf

2022-05-06 19:29 UTC, dikkini commented
А покажи пожалуйста как инициализировать в таком случае клиент в постгресу. Добавь код [сюда](https://github.com/theartofdevel/production-service/blob/6c04f98e236f7ab052d656c4b615e59ff538f397/app/internal/app/app.go#L30) и инициализируй клиента к PostgreSQL.

2022-05-07 06:49 UTC, KindOf commented
@dikkini добавил пример. Но мне кажется способ инициализации pg pool будет зависить от того как сторейджи буду организованы. Package app should be abstracted from particular storage implementation.

2022-05-07 08:13 UTC, dikkini commented on app/internal/app/app.go
> +		return App{
сделай здесь фатал и я смержу. мне нравится

2022-05-07 08:13 UTC, dikkini requested changes
давай упадем если не удалось создать клиента, потому что без клиента к БД приложение не будет работать и я смержу

2022-05-07 09:25 UTC, KindOf commented on app/internal/app/app.go
> +		return App{
доне

2022-05-07 12:47 UTC, merged

2022-10-11 07:41 UTC, dikkini commented
Можешь предложить организацию репозиториев.

Я вот думал все же чистую архитектуру начать использовать.

Попробуем?
On 7 May 2022, 09:49 +0300, Ihor ***@***.***>, wrote:
> @dikkini добавил пример. Но мне кажется способ инициализации pg pool будет зависить от того как сторейджи буду организованы. Package app should be abstracted from particular storage implementation.
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID: ***@***.***>